Repository arana-db/arana, pull requests merged in 2022-06, with the labels that each got.

#195 Fer: add new shard algorithm.
  conf/config.yaml
  pkg/boot/discovery.go
  pkg/config/model.go
  pkg/runtime/rule/shard.go
  pkg/runtime/rule/shard_expr.go
  pkg/runtime/rule/shard_expr_parse.go
  pkg/runtime/rule/shard_expr_parse_test.go
  pkg/runtime/rule/shard_expr_type.go
  pkg/runtime/rule/shard_expr_type_test.go
  testdata/fake_bootstrap.yaml
  testdata/fake_config.yaml
Labels: enhancement, sharding

#209 feat: make configurations as real sharding tables
  conf/config.yaml
  docker-compose.yaml
  go.mod
  justfile
  pkg/boot/discovery.go
  scripts/init.sql
  scripts/sequence.sql
  scripts/sharding.sql
  test/integration_test.go
Labels: refactor

#215 update readme.
  README.md
  docs/pics/arana-architecture.png
Labels: documentation

#214 feat: on duplicate key update
  pkg/runtime/optimize/optimizer.go
  test/integration_test.go
Labels: enhancement, SQL

#210 support insert select stmt for non-sharding table
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/ast_test.go
  pkg/runtime/ast/insert.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/optimize/optimizer_test.go
  pkg/runtime/plan/insert_select.go
Labels: enhancement, do not merge, SQL

#216 chore: fix some small issue.
  README.md
  pkg/runtime/rule/shard_expr_parse.go
Labels: documentation

#207 Ftr: support drop index ast
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/drop_index.go
  pkg/runtime/ast/proto.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/drop_index.go
Labels: enhancement, SQL

#220 fix: #219
  pkg/executor/redirect.go
  pkg/mysql/client.go
  pkg/mysql/client_test.go
  pkg/mysql/conn.go
  pkg/mysql/utils.go
Labels: bug

#223 feat: implement group/reduce dataset
  pkg/dataset/chain.go
  pkg/dataset/filter.go
  pkg/dataset/filter_test.go
  pkg/dataset/fuse.go
  pkg/dataset/fuse_test.go
  pkg/dataset/group_reduce.go
  pkg/dataset/group_reduce_test.go
  pkg/dataset/transform.go
  pkg/dataset/transform_test.go
  test/integration_test.go
Labels: enhancement, refactor

#231 fix: fix drop index need to send each shard
  pkg/executor/redirect.go
  pkg/mysql/rows/virtual_row.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/drop_index.go
  pkg/runtime/plan/transparent.go
  pkg/runtime/rule/shard_expr_parse.go
  scripts/init.sql
  scripts/sharding.sql
  test/integration_test.go
  test/suite.go
Labels: bug, SQL

#233 feat: peekable and parallel dataset
  pkg/dataset/dataset.go
  pkg/dataset/parallel.go
  pkg/dataset/parallel_test.go
Labels: enhancement, refactor

#217 Support "show columns from tables" SQL statement.
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/show.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/show_columns.go
  test/integration_test.go
Labels: enhancement, SQL

#245 fix: #240
  pkg/mysql/execute_handle.go
  pkg/mysql/server.go
Labels: bug, protocol

#250 feat(*): add orderedDataset
  pkg/dataset/ordered.go
  pkg/dataset/ordered_test.go
  pkg/dataset/priority_queue.go
  pkg/dataset/priority_queue_test.go
Labels: enhancement, kernel

#255 fix: remove some vitess types
  docker-compose.yaml
  pkg/constants/mysql/type.go
  pkg/constants/mysql/type_test.go
  pkg/mysql/rows.go
  pkg/mysql/server.go
Labels: refactor, protocol

#251 feat: add error log
  pkg/mysql/execute_handle.go
Labels: enhancement, kernel
