Repository arana-db/arana, pull requests merged in 2022-10, with the labels that each got.

#432 fix: incorrect behavior for intdiv operator
  pkg/mysql/rows/virtual_row.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/expression_atom.go
  pkg/runtime/plan/dml/mapping.go
  test/integration_test.go
Labels: bug, SQL

#438 feat:solo slow logger
  conf/bootstrap.yaml
  pkg/boot/boot.go
  pkg/boot/discovery.go
  pkg/boot/proto.go
  pkg/config/model.go
  pkg/mysql/server.go
  pkg/runtime/namespace/command.go
  pkg/runtime/namespace/namespace.go
  pkg/runtime/runtime.go
  pkg/util/log/logging.go
Labels: observability, kernel

#441 docs:updated features
  README.md
  README_CN.md
  README_ZH.md
Labels: doc

#440 fix #392
  conf/bootstrap.docker.yaml
  docker-compose.yaml
Labels: bug

#445 style: use root path
  conf/bootstrap.yaml
Labels: config

#448 Format readme.
  README.md
Labels: doc

#450 fix: compatibility with mysql8.0
  pkg/admin/router/clusters.go
  pkg/admin/router/db_groups.go
  pkg/admin/router/misc.go
  pkg/boot/boot.go
  pkg/boot/discovery.go
  pkg/config/api.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/diff.go
  pkg/config/equals.go
  pkg/config/etcd/etcd.go
  pkg/config/file/file.go
  pkg/config/nacos/nacos.go
  pkg/config/nacos/nacos_test.go
  pkg/executor/redirect.go
  pkg/proto/runtime.go
  pkg/runtime/ast/expression_atom.go
  pkg/runtime/ast/restore.go
  pkg/runtime/function2/abs_test.go
  pkg/runtime/optimize/dml/select.go
  pkg/runtime/plan/dal/analyze_table.go
  pkg/runtime/plan/dml/mapping.go
  pkg/runtime/plan/dml/simple_select.go
  pkg/runtime/rule/shard_expr_type_test.go
  pkg/runtime/runtime.go
  pkg/trace/jaeger/jaeger.go
  pkg/util/match/slice_match.go
  test/integration_test.go
  testdata/mock_runtime.go
Labels: bug

#439 refactor: issue #435
  pkg/boot/discovery.go
  pkg/boot/discovery_import.go
  pkg/boot/discovery_watch.go
  pkg/boot/proto.go
  pkg/config/api.go
  pkg/config/api_test.go
  pkg/config/config.go
  pkg/config/config_reader.go
  pkg/config/config_test.go
  pkg/config/config_watcher.go
  pkg/config/config_writer.go
  pkg/config/mock/mock_config.go
  pkg/config/nacos/nacos_test.go
  pkg/config/options.go
  pkg/config/path.go
  pkg/config/tenant.go
  pkg/constants/mysql/collations.go
  pkg/merge/impl/group/group_stream_merge_rows.go
  pkg/mysql/auth.go
  pkg/mysql/utils.go
  pkg/proto/hint/hint.go
  pkg/runtime/plan/dml/drop_weak.go
  testdata/mock_config.go
  third_party/base58/doc.go
Labels: refactor, config

#451 Feat:add changelog github workflow action
  .github/workflows/changelog.yml
Labels: release

#467 fix：针对集成测试的参数进行逻辑校验
  integration_test/scene/db/integration_test.go
  integration_test/scene/db_tbl/integration_test.go
  integration_test/scene/db_tbl_rw/integration_test.go
  integration_test/scene/tbl/integration_test.go
  test/dataset.go
Labels: bug

#471 feat: docker integration with arana ui
  .dockerignore
  Dockerfile
  pkg/admin/admin.api.yaml
  pkg/admin/admin.go
  pkg/config/mock/mock_config.go
Labels: UI, docker

#461 refine logger
  Dockerfile
  conf/bootstrap.yaml
  pkg/boot/discovery.go
  pkg/config/model.go
  pkg/util/log/logging.go
Labels: enhancement

#462 feat: support SHOW MASTER STATUS
  pkg/executor/redirect.go
  pkg/runtime/ast/proto.go
  pkg/runtime/ast/show.go
  pkg/runtime/optimize/dal/show_master_status.go
  pkg/runtime/plan/dal/show_master_status.go
  pkg/runtime/plan/dal/show_master_status_test.go
Labels: SQL
