Repository arana-db/arana, pull requests merged in 2022-05, with the labels that each got.

#139 add iterRow
  go.mod
  pkg/constants/mysql/constants.go
  pkg/mysql/client.go
  pkg/mysql/iterator.go
  pkg/mysql/statement.go
  pkg/runtime/runtime.go
  third_party/pools/resource_pool.go
  third_party/pools/resource_pool_flaky_test.go
Labels: enhancement, sharding

#157 support insert stmt rewrite and add mock schema loader
  pkg/proto/runtime.go
  pkg/proto/schema_manager/loader.go
  pkg/proto/schema_manager/loader_test.go
  pkg/runtime/ast/insert.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/optimize/optimizer_test.go
  testdata/mock_runtime.go
Labels: enhancement, SQL

#152 feat: drop table
  go.mod
  pkg/executor/redirect.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/drop_table.go
  pkg/runtime/ast/proto.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/drop_table.go
  pkg/runtime/plan/transparent.go
  test/integration_test.go
Labels: enhancement, SQL

#156 improve: local config file refinement
  cmd/main.go
  cmd/start/start.go
  cmd/tools/tools.go
  conf/bootstrap.yaml
  conf/config.yaml
  go.mod
  go.sum
  justfile
  pkg/config/config.go
  pkg/config/etcd/etcd_test.go
  pkg/config/file/file.go
  pkg/config/model.go
  pkg/config/model_test.go
  pkg/config/nacos/nacos_test.go
  pkg/constants/env.go
  pkg/executor/redirect.go
  pkg/metrics/metrics.go
  pkg/mysql/conn.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/rule/shard_script.go
Labels: enhancement, refactor, config

#161 feat: support non-db login
  pkg/constants/mysql/constants.go
  pkg/executor/redirect.go
  pkg/mysql/server.go
  pkg/proto/interface.go
  pkg/security/tenant.go
Labels: enhancement

#171 chore: change port of docker-compose, add local server example
  docker-compose.yaml
  example/local_server/main.go
Labels: test

#173 add table_schema filter to metadata loader sql
  pkg/proto/schema_manager/loader.go
Labels: sharding

#153 Ftr: 针对shard之后的查询结果做聚合
  pkg/mysql/rows.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/union.go
  pkg/runtime/runtime.go
  pkg/transformer/aggr_loader.go
  pkg/transformer/combiner.go
  test/integration_test.go
Labels: enhancement, SQL

#158 return data to client via channel
  go.mod
  go.sum
  pkg/executor/redirect.go
  pkg/mysql/client.go
  pkg/mysql/client_test.go
  pkg/mysql/conn.go
  pkg/mysql/execute_handle.go
  pkg/mysql/iterator.go
  pkg/mysql/result.go
  pkg/mysql/server.go
  pkg/mysql/statement.go
  pkg/proto/data.go
  pkg/proto/interface.go
  pkg/proto/schema_manager/loader.go
  pkg/runtime/optimize/optimizer_test.go
  pkg/runtime/plan/drop_table.go
  pkg/runtime/plan/show_databases.go
  pkg/runtime/plan/show_tables.go
  pkg/runtime/plan/simple_delete.go
  pkg/runtime/plan/simple_insert.go
  pkg/runtime/plan/simple_select.go
  pkg/runtime/plan/truncate.go
  pkg/runtime/plan/union.go
  pkg/runtime/plan/update.go
  pkg/runtime/runtime.go
  pkg/transformer/combiner.go
  test/integration_test.go
Labels: enhancement, refactor

#181 feat: simple join
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/join.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/simple_join.go
  test/integration_test.go
Labels: enhancement

#163 Support single db, multi-table order by SQL
  pkg/runtime/plan/simple_select.go
Labels: enhancement, SQL

#185 fix #155 return empty rows when query from information_schema.columns
  pkg/runtime/plan/simple_select.go
Labels: bug

#184 feat: alter table statement
  pkg/executor/redirect.go
  pkg/runtime/ast/alter_table.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/ast_test.go
  pkg/runtime/ast/model.go
  pkg/runtime/ast/proto.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/optimize/optimizer_test.go
  pkg/runtime/plan/alter_table.go
  pkg/runtime/plan/transparent.go
  test/integration_test.go
Labels: enhancement, SQL

#192 Fix: fix readme dingtalk group image link.
  README.md
Labels: documentation

#189 feat:show index
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/show_index.go
Labels: enhancement, SQL

#190 support "desc student id" grammar
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/ast_test.go
  pkg/runtime/ast/describe.go
  pkg/runtime/ast/show.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/describle.go
Labels: enhancement, SQL

#201 fix: execute union plan correctly
  pkg/runtime/plan/union.go
Labels: bug
