Repository arana-db/arana, pull requests merged in 2022-09, with the labels that each got.

#391 Release: Support commit-chglog tool.
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  CHANGELOG.md
Labels: release

#399 fix :bug: HTTP API For UI
  pkg/admin/router/nodes.go
Labels: config

#395 add Value.ToIntString()
  pkg/runtime/rule/evaluator.go
  pkg/runtime/rule/shard_expr.go
  pkg/runtime/rule/shard_expr_parse.go
  pkg/runtime/rule/shard_expr_type.go
  pkg/runtime/rule/shard_expr_type_test.go
Labels: refactor, sharding

#405 Feature: support shadow type match regex (#365)
  conf/config.yaml
  integration_test/config/shadow/config.yaml
  integration_test/scene/shadow/integration_test.go
  integration_test/testcase/casetest.yaml
  pkg/constants/const.go
  pkg/proto/rule/shadow.go
  pkg/runtime/ast/expression_atom.go
  pkg/runtime/optimize/dml/delete.go
  pkg/runtime/optimize/dml/insert.go
  pkg/runtime/optimize/dml/select.go
  pkg/runtime/optimize/dml/update.go
  pkg/runtime/optimize/sharder.go
  pkg/runtime/plan/dal/show_tables.go
  pkg/runtime/rule/evaluator.go
  scripts/init.sql
  scripts/sharding.sql
  test/dataset.go
Labels: shadow

#400 feat(sequence): add group sequence implementation
  pkg/sequence/group/group.go
  pkg/sequence/group/group_test.go
Labels: enhancement, sharding

#413 feat:filter prefix table name
  pkg/dataset/chain.go
  pkg/dataset/filter.go
  pkg/runtime/plan/dal/constant.go
  pkg/runtime/plan/dal/show_table_status.go
  pkg/runtime/plan/dal/show_tables.go
Labels: bug

#412 Feat/shadow
  integration_test/config/shadow/config.yaml
  integration_test/scene/shadow/integration_test.go
  integration_test/testcase/casetest.yaml
  pkg/proto/rule/database_table.go
  pkg/proto/rule/database_table_test.go
  pkg/runtime/optimize/dml/delete.go
  pkg/runtime/optimize/dml/insert.go
  pkg/runtime/optimize/dml/select.go
  pkg/runtime/optimize/dml/update.go
  scripts/sharding.sql
  test/dataset.go
Labels: shadow

#409 feat:add analyze table
  go.mod
  pkg/executor/redirect.go
  pkg/runtime/ast/analyze_table.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/proto.go
  pkg/runtime/optimize/dal/analyze_table.go
  pkg/runtime/plan/dal/analyze_table.go
  test/integration_test.go
Labels: SQL

#414 feat: redefine object fields for arana-UI
  pkg/admin/router/clusters.go
  pkg/admin/router/db_groups.go
  pkg/boot/discovery.go
  pkg/boot/proto.go
Labels: UI

#423 ci: add staticcheck
  .dockerignore
  .github/workflows/reviewdog.yml
  .pre-commit-config.yaml
  cmd/start/start.go
  go.mod
  pkg/admin/router/db_groups.go
  pkg/boot/discovery.go
  pkg/config/config.go
  pkg/config/equals.go
  pkg/config/etcd/etcd_test.go
  pkg/config/model.go
  pkg/constants/mysql/collations.go
  pkg/dataset/virtual_test.go
  pkg/merge/impl/group/group_stream_merge_rows.go
  pkg/mysql/auth.go
  pkg/mysql/auth_test.go
  pkg/mysql/client.go
  pkg/mysql/rows/virtual_row.go
  pkg/resultx/resultx.go
  pkg/runtime/optimize/dml/select.go
  pkg/runtime/rule/shard_expr_type.go
  pkg/runtime/rule/shard_script.go
  pkg/schema/loader.go
  pkg/trace/jaeger/jaeger.go
  pkg/util/bytefmt/bytefmt.go
  pkg/util/env/env.go
  staticcheck.conf
Labels: CI/CD

#430 feat: support slow log
  conf/config.yaml
  pkg/boot/boot.go
  pkg/constants/const.go
  pkg/executor/redirect.go
  pkg/runtime/namespace/command.go
  pkg/runtime/namespace/namespace.go
  pkg/runtime/runtime.go
Labels: kernel
