Repository arana-db/arana, pull requests merged in 2022-03, with the labels that each got.

#73 fixes unit test parameter order.
  pkg/config/config_test.go
  pkg/constants/mysql/type_test.go
  pkg/executor/redirect_test.go
  pkg/filters/filters_test.go
Labels: test

#75 add unit test for fields.go, result.go, rows.go.
  pkg/mysql/fields_test.go
  pkg/mysql/result_test.go
  pkg/mysql/rows_test.go
Labels: test

#78 Optimize unit test code.
  pkg/config/config_test.go
  pkg/constants/mysql/type_test.go
  pkg/executor/redirect_test.go
  pkg/filters/filters_test.go
Labels: test

#74 feat: implement simple sharding over runtime API
  .gitignore
  .licenserc.yaml
  docker/docker-compose.yaml
  docker/scripts/sequence.sql
  docker/scripts/sharding.sql
  go.mod
  go.sum
  pkg/executor/redirect.go
  pkg/mysql/client_test.go
  pkg/mysql/conn.go
  pkg/mysql/conn_test.go
  pkg/mysql/result.go
  pkg/mysql/server.go
  pkg/proto/data.go
  pkg/proto/interface.go
  pkg/proto/rule/range_test.go
  pkg/proto/rule/rule.go
  pkg/proto/rule/rule_test.go
  pkg/proto/runtime.go
  pkg/resource/data_source.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/ast_crud.go
  pkg/runtime/ast/ast_describe.go
  pkg/runtime/ast/ast_expression.go
  pkg/runtime/ast/ast_expression_atom.go
  pkg/runtime/ast/ast_function.go
  pkg/runtime/ast/ast_predicate.go
  pkg/runtime/ast/ast_select_element.go
  pkg/runtime/ast/ast_show.go
  pkg/runtime/ast/ast_test.go
  pkg/runtime/ast/ast_union.go
  pkg/runtime/ast/types.go
  pkg/runtime/context/context.go
  pkg/runtime/function/function.go
  pkg/runtime/function/function_test.go
  pkg/runtime/namespace/command.go
  pkg/runtime/namespace/namespace.go
  pkg/runtime/namespace/namespace_test.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/optimize/optimizer_test.go
  pkg/runtime/optimize/sharder.go
  pkg/runtime/optimize/sharder_test.go
  pkg/runtime/plan/misc.go
  pkg/runtime/plan/simple.go
  pkg/runtime/plan/union.go
  pkg/runtime/rule/evaluator.go
  pkg/runtime/rule/shard.go
  pkg/runtime/runtime.go
  pkg/util/tableprint/print_table.go
  test/integration_test.go
  testdata/mock_runtime.go
  testdata/testdata.go
Labels: enhancement

#79 fix: client exit ,but do not send com_quit
  pkg/mysql/server.go
Labels: bug

#89 add unit test.
  pkg/proto/interface_test.go
  pkg/proto/rule/topology_test.go
Labels: test

#90 feat: integrate config v2 and implement simple tx backbone
  cmd/cmd.go
  go.mod
  go.sum
  pkg/boot/boot.go
  pkg/boot/discovery.go
  pkg/boot/discovery_over_etcd.go
  pkg/boot/discovery_over_file.go
  pkg/boot/discovery_over_file_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/db.go
  pkg/config/db_test.go
  pkg/config/etcd.go
  pkg/config/etcd_test.go
  pkg/config/testdata/config.yaml
  pkg/executor/redirect.go
  pkg/executor/redirect_test.go
  pkg/mysql/server.go
  pkg/proto/interface.go
  pkg/proto/interface_test.go
  pkg/proto/rule/attributes.go
  pkg/proto/rule/attributes_test.go
  pkg/proto/rule/range.go
  pkg/proto/rule/rule.go
  pkg/proto/runtime.go
  pkg/resource/data_source.go
  pkg/runtime/context/context.go
  pkg/runtime/namespace/namespace.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/security/tenant.go
  pkg/security/tenant_test.go
  test/integration_test.go
  testdata/fake_config.yaml
  testdata/mock_data.go
  testdata/mock_runtime.go
  testdata/mock_select_element.go
  testdata/mock_sequence.go
Labels: enhancement

#100 fix: parse dbname from USE_DATABASE correctly
  pkg/mysql/conn.go
  pkg/mysql/server.go
Labels: bug

#91 Ftr: select db by read/write weight in namespace
  pkg/runtime/context/context.go
  pkg/runtime/namespace/namespace.go
  pkg/runtime/namespace/namespace_test.go
Labels: enhancement
