Repository arana-db/arana, pull requests merged in 2022-11, with the labels that each got.

#464 feat(config): add tenant&cluster config support
  pkg/boot/discovery.go
  pkg/config/config_writer.go
Labels: config

#481 add node config support (#464)
  pkg/admin/router/nodes.go
  pkg/boot/discovery.go
  pkg/boot/proto.go
  pkg/config/api.go
  pkg/config/tenant.go
Labels: config

#480 feat(config): add sharding_rule table config support
  pkg/boot/discovery.go
Labels: config

#474 feat: add CAST function placeholder.
  pkg/runtime/function2/cast.go
  pkg/runtime/function2/cast_test.go
Labels: SQL

#497 feat: md5
  pkg/runtime/function2/md5.go
  pkg/runtime/function2/md5_test.go
Labels: SQL

#508 feat:length
  pkg/runtime/function2/length.go
  pkg/runtime/function2/length_test.go
Labels: SQL

#510 feat: Support MySQL SHA1 & SHA function
  pkg/runtime/function2/sha1.go
  pkg/runtime/function2/sha1_test.go
Labels: SQL

#509 fix(admin): fix cluster/group crud api
  pkg/admin/admin.api.yaml
  pkg/admin/router/clusters.go
  pkg/admin/router/db_groups.go
  pkg/boot/discovery.go
Labels: config

#504 fix: when args of CONCAT have any NULL, it should return NULL
  pkg/runtime/function2/concat.go
  pkg/runtime/function2/concat_test.go
Labels: bug

#512 feat: Support MySQL Cast Charset function
  pkg/runtime/function2/cast_charset.go
  pkg/runtime/function2/char_charset_test.go
  pkg/util/charsetconv/charsetconv.go
  pkg/util/charsetconv/charsetconv_test.go
Labels: SQL

#431 feat: add service registry
  cmd/start/start.go
  conf/bootstrap.yaml
  example/service_discovery/etcd/main.go
  pkg/boot/discovery.go
  pkg/boot/options.go
  pkg/boot/proto.go
  pkg/config/model.go
  pkg/registry/base/base.go
  pkg/registry/discovery.go
  pkg/registry/etcd/discovery.go
  pkg/registry/etcd/registery.go
  pkg/registry/registry.go
  pkg/registry/store/etcdv3.go
  pkg/registry/store/store.go
Labels: config

#511 feat: cast unsign func
  pkg/runtime/function2/cast.go
  pkg/runtime/function2/cast_test.go
Labels: SQL

#506 feat: support the func concast_ws
  pkg/runtime/function2/cast.go
  pkg/runtime/function2/concat_ws.go
  pkg/runtime/function2/concat_ws_test.go
Labels: SQL

#496 feat: sync variables between arana and mysql
  .github/workflows/changelog.yml
  example/service_discovery/etcd/main.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/config_watcher.go
  pkg/config/config_writer.go
  pkg/config/model.go
  pkg/config/path.go
  pkg/config/tenant.go
  pkg/executor/redirect.go
  pkg/mysql/client.go
  pkg/mysql/conn.go
  pkg/mysql/server.go
  pkg/proto/interface.go
  pkg/proto/runtime.go
  pkg/registry/etcd/registery.go
  pkg/registry/registry.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/ast_test.go
  pkg/runtime/ast/expression_atom.go
  pkg/runtime/ast/proto.go
  pkg/runtime/ast/set_variable.go
  pkg/runtime/context/context.go
  pkg/runtime/function2/cast_charset.go
  pkg/runtime/function2/cast_nchar.go
  pkg/runtime/function2/ceil_test.go
  pkg/runtime/function2/concat.go
  pkg/runtime/function2/exp.go
  pkg/runtime/function2/floor_test.go
  pkg/runtime/function2/length.go
  pkg/runtime/function2/length_test.go
  pkg/runtime/function2/md5.go
  pkg/runtime/function2/md5_test.go
  pkg/runtime/function2/pi.go
  pkg/runtime/function2/sha1.go
  pkg/runtime/function2/sha1_test.go
  pkg/runtime/function2/sqrt.go
  pkg/runtime/misc/extvalue/extvalue.go
  pkg/runtime/optimize/dal/show_replicas.go
  pkg/runtime/optimize/ddl/set_variable.go
  pkg/runtime/optimize/sharder.go
  pkg/runtime/plan/dal/show_replicas.go
  pkg/runtime/plan/ddl/set_variable.go
  pkg/runtime/runtime.go
  pkg/util/charsetconv/charsetconv.go
  pkg/util/charsetconv/charsetconv_test.go
  testdata/mock_runtime.go
Labels: refactor, kernel

#515 feat: support Mysql Upper Function
  pkg/runtime/function2/upper.go
  pkg/runtime/function2/upper_test.go
Labels: SQL

#516 feat(admin): add table open api
  pkg/admin/admin.api.yaml
  pkg/admin/router/clusters.go
  pkg/admin/router/db_groups.go
  pkg/admin/router/tables.go
  pkg/boot/discovery.go
Labels: config

#526 feat: Support MySQL Lower function
  pkg/runtime/function/lower.go
  pkg/runtime/function/lower_test.go
Labels: SQL

#525 fix: add jaeger into docker compose file
  conf/bootstrap.docker.yaml
  docker-compose.yaml
  pkg/boot/discovery.go
  pkg/boot/options.go
  pkg/boot/proto.go
  pkg/config/model.go
Labels: enhancement, observability

#523 feat(sql): support show replica status SQL statement. (arana#494)
  go.mod
  go.sum
  pkg/executor/redirect.go
  pkg/runtime/ast/proto.go
  pkg/runtime/ast/show.go
  pkg/runtime/optimize/dal/show_replica_status.go
  pkg/runtime/plan/dal/show_replica_status.go
  test/integration_test.go
Labels: SQL

#528 feat: add mysql right function
  pkg/runtime/function/right.go
  pkg/runtime/function/right_test.go
Labels: SQL

#527 add support for optimize table statement
  go.mod
  go.sum
  pkg/executor/redirect.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/optimize_table.go
  pkg/runtime/ast/proto.go
  pkg/runtime/optimize/ddl/optimize_table.go
  pkg/runtime/plan/ddl/optimize_table.go
  test/integration_test.go
Labels: SQL

#547 feat:Support MySQL POWER and ROUND function.#456
  go.mod
  go.sum
  pkg/runtime/function/power.go
  pkg/runtime/function/power_test.go
  pkg/runtime/function/round.go
  pkg/runtime/function/round_test.go
Labels: SQL

#548 feat: implement new visitor based shard computer
  go.mod
  go.sum
  pkg/boot/boot.go
  pkg/boot/discovery.go
  pkg/proto/data.go
  pkg/proto/rule/database_table.go
  pkg/proto/rule/rule.go
  pkg/proto/rule/rule_test.go
  pkg/proto/rule/shards.go
  pkg/proto/rule/shards_test.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/expression_atom.go
  pkg/runtime/ast/function.go
  pkg/runtime/ast/table_source.go
  pkg/runtime/ast/visitor.go
  pkg/runtime/js/doc.go
  pkg/runtime/js/function.go
  pkg/runtime/js/function_test.go
  pkg/runtime/js/scripts/cast.js
  pkg/runtime/js/scripts/math.js
  pkg/runtime/js/scripts/string.js
  pkg/runtime/js/scripts/time.js
  pkg/runtime/js/vm.go
  pkg/runtime/js/vm_test.go
  pkg/runtime/misc/extvalue/extvalue.go
  pkg/runtime/misc/extvalue/extvalue_test.go
  pkg/runtime/misc/extvalue/visitor.go
  pkg/runtime/misc/pair.go
  pkg/runtime/optimize/dml/aggregate_visitor.go
  pkg/runtime/optimize/dml/aggregate_visitor_test.go
  pkg/runtime/optimize/dml/insert.go
  pkg/runtime/optimize/dml/select.go
  pkg/runtime/optimize/dml/update.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/optimize/shard_visitor.go
  pkg/runtime/optimize/shard_visitor_test.go
  pkg/runtime/optimize/sharder.go
  pkg/runtime/plan/ddl/set_variable.go
  pkg/runtime/plan/dml/mapping.go
  pkg/runtime/rule/evaluator.go
  pkg/runtime/rule/evaluator_test.go
  pkg/runtime/rule/route.go
  pkg/runtime/rule/route_test.go
  pkg/runtime/rule/shard.go
  pkg/runtime/rule/shard_expr.go
  pkg/runtime/rule/shard_expr_parse.go
  pkg/runtime/rule/shard_expr_parse_test.go
  pkg/runtime/rule/shard_expr_test.go
  pkg/runtime/rule/shard_expr_type.go
  pkg/runtime/rule/shard_expr_type_test.go
  pkg/runtime/runtime.go
  testdata/mock_runtime.go
Labels: refactor, kernel
