Repository arana-db/arana, pull requests merged in 2022-08, with the labels that each got.

#315 hint fullscan
  pkg/proto/hint/hint.go
  pkg/runtime/optimize/dml/insert.go
  pkg/runtime/optimize/dml/select.go
  pkg/runtime/optimize/dml/update.go
  pkg/runtime/optimize/hints.go
  pkg/runtime/optimize/optimizer.go
  pkg/sequence/snowflake/snowflake.go
  test/integration_test.go
Labels: hint

#335 fix:loop Reconnecting
  pkg/mysql/execute_handle.go
Labels: bug

#336 feat(config): add config updater api
  pkg/boot/discovery.go
  pkg/boot/proto.go
Labels: UI

#349 fix: shadow_show not exists
  scripts/init.sql
Labels: shadow

#352 add http server api for cluster.
  pkg/admin/router/clusters.go
  pkg/boot/boot.go
  pkg/boot/discovery.go
  pkg/boot/proto.go
  pkg/dataset/reduce.go
Labels: config

#369 improve: show_table_status ast node
  integration_test/scene/db_tbl_rw/integration_test.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/ast_test.go
  pkg/runtime/ast/misc.go
  pkg/runtime/ast/show.go
Labels: refactor

#371 add http api for nodes#344
  pkg/admin/router/nodes.go
Labels: config

#380 fix snowflake id offset
  pkg/sequence/snowflake/snowflake.go
Labels: bug

#376 feat:add show warnings
  pkg/executor/redirect.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/proto.go
  pkg/runtime/ast/show.go
  pkg/runtime/optimize/dal/show_warnings.go
  pkg/runtime/plan/dal/show_warnings.go
Labels: SQL

#381 [chore] add config center doc & unit test.
  pkg/config/README.md
  pkg/constants/env_test.go
  pkg/constants/mysql/constants_test.go
  pkg/constants/mysql/type_test.go
Labels: test

#382 feat: use etcd in docker compose by default
  cmd/start/start.go
  conf/bootstrap.docker.yaml
  docker-compose.yaml
  example/local_server/main.go
  pkg/boot/discovery.go
  test/suite.go
Labels: docker
