Repository arana-db/arana, pull requests merged in 2022-07, with the labels that each got.

#264 Chore: fix arana dependency order.
  .github/workflows/release.yml
  README.md
  go.mod
  go.sum
Labels: refactor

#270 fix: remove some unnecessary ut to resolve CI failure
  .github/workflows/reviewdog.yml
  .pre-commit-config.yaml
  test/integration_test.go
  test/suite.go
Labels: test, refactor

#266 fix: fix sequence create table sql
  pkg/sequence/snowflake/snowflake.go
Labels: bug, sharding

#269 fix: #256
  pkg/executor/redirect.go
  pkg/mysql/conn.go
  pkg/mysql/execute_handle.go
  third_party/pools/resource_pool.go
Labels: enhancement, refactor

#275 fix:show index
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/show.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/show_index.go
Labels: bug, SQL

#271 fix: #262
  conf/config.yaml
  pkg/config/model.go
  pkg/mysql/client.go
  pkg/mysql/execute_handle.go
  pkg/runtime/runtime.go
  pkg/util/bytefmt/bytefmt.go
  pkg/util/bytefmt/bytefmt_test.go
  pkg/util/log/logging.go
Labels: enhancement, protocol

#274 feat:new logo
  README.md
  README_CN.md
  README_ZH.md
  docs/pics/arana-blue.png
  docs/pics/arana-db-blue.png
  docs/pics/arana-db-v0.2.sketch
  docs/pics/arana-main.png
Labels: documentation

#259 support group by plan
  pkg/dataset/chain.go
  pkg/dataset/group_reduce.go
  pkg/dataset/group_reduce_test.go
  pkg/merge/aggregator/init.go
  pkg/merge/aggregator/load_agg.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/group_plan.go
  pkg/transformer/aggr_loader.go
  pkg/transformer/combiner.go
Labels: enhancement

#254 Ftr: create index
  pkg/executor/redirect.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/create_index.go
  pkg/runtime/ast/proto.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/create_index.go
  pkg/runtime/plan/transparent.go
  test/integration_test.go
Labels: enhancement, SQL

#285 Bug: fix issue #229
  conf/config.yaml
  integration_test/config/db/config.yaml
  integration_test/scene/db/config.yaml
  integration_test/scene/db/integration_test.go
  integration_test/scene/db_tbl/config.yaml
  integration_test/scene/tbl/config.yaml
  pkg/boot/discovery.go
  pkg/config/model.go
Labels: bug, sharding

#286 improve: expose vconn for runtime and tx
  Makefile
  pkg/boot/boot.go
  pkg/proto/interface.go
  pkg/proto/runtime.go
  pkg/proto/schema.go
  pkg/runtime/context/context.go
  pkg/runtime/optimize/alter_table.go
  pkg/runtime/optimize/create_index.go
  pkg/runtime/optimize/describe.go
  pkg/runtime/optimize/drop_trigger.go
  pkg/runtime/optimize/insert.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/optimize/optimizer_test.go
  pkg/runtime/optimize/select.go
  pkg/runtime/optimize/show_columns.go
  pkg/runtime/optimize/update.go
  pkg/runtime/runtime.go
  pkg/schema/loader.go
  pkg/schema/loader_test.go
  testdata/mock_runtime.go
  testdata/mock_schema.go
Labels: refactor, kernel

#288 feat: hint master
  conf/config.yaml
  go.mod
  go.sum
  integration_test/config/db_tbl/config.yaml
  integration_test/scripts/db_tbl/sharding.sql
  pkg/runtime/context/context.go
  pkg/runtime/namespace/namespace.go
  pkg/runtime/runtime.go
  scripts/sharding.sql
  test/integration_test.go
Labels: enhancement, hint, read-write-split

#295 support group by clause column complement
  pkg/dataset/group_reduce.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/select_element.go
  pkg/runtime/optimize/dml/select.go
  pkg/runtime/plan/dml/group_plan.go
Labels: enhancement, sharding

#290 add unit test.
  pkg/dataset/virtual_test.go
  pkg/mysql/auth_test.go
  pkg/mysql/rows_test.go
Labels: test

#306 add unit test.
  pkg/config/file/file.go
  pkg/runtime/rule/iterator_test.go
  pkg/runtime/rule/shard_expr_test.go
  pkg/runtime/runtime.go
  testdata/mock_rule.go
Labels: test

#246 refactor schemanager cache to lru cache
  pkg/schema/loader.go
Labels: refactor, kernel

#302 fix: fix sequence bug
  integration_test/config/db/config.yaml
  integration_test/config/db_tbl/config.yaml
  integration_test/config/tbl/config.yaml
  pkg/boot/boot.go
  pkg/boot/discovery.go
  pkg/config/model.go
  pkg/proto/rule/rule.go
  pkg/proto/runtime.go
  pkg/proto/sequence.go
  pkg/runtime/namespace/command.go
  pkg/runtime/namespace/namespace.go
  pkg/runtime/namespace/namespace_test.go
  pkg/runtime/optimize/dml/insert.go
  pkg/runtime/runtime_test.go
  pkg/schema/loader_test.go
  pkg/sequence/group/group.go
  pkg/sequence/sequence.go
  pkg/sequence/sequence_test.go
  pkg/sequence/snowflake/snowflake.go
  pkg/sequence/snowflake/snowflake_test.go
  testdata/fake_config.yaml
Labels: refactor, sharding

#312 feat: max_allowed_packet is set by the user
  conf/config.yaml
  pkg/mysql/client.go
Labels: refactor, protocol

#316 Fix new sequence
  pkg/sequence/snowflake/snowflake.go
  test/integration_test.go
Labels: bug, sharding

#328 debug: listen capabilities fix:#317
  pkg/mysql/conn.go
  pkg/mysql/execute_handle.go
  pkg/mysql/server.go
Labels: bug

#307 Support "show collation" SQL statement.
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/proto.go
  pkg/runtime/ast/show.go
  pkg/runtime/optimize/dal/show_collation.go
  pkg/runtime/plan/dal/show_collation.go
  test/integration_test.go
Labels: SQL

#323 add unit test.
  pkg/config/api_test.go
  pkg/config/etcd/etcd_test.go
  pkg/config/file/file.go
  pkg/config/file/file_test.go
  pkg/config/model_test.go
  testdata/fake_bootstrap.yaml
  testdata/fake_config.yaml
  testdata/fake_empty_config.yaml
  testdata/mock_config.go
  testdata/mock_data.go
Labels: test
