Repository arana-db/arana, pull requests merged in 2022-04, with the labels that each got.

#119 add testcontainer as integration testing tool
  docker/scripts/sharding.sql
  go.mod
  go.sum
  test/testcontainer_mysql.go
  test/testcontainer_mysql_test.go
Labels: enhancement

#122 chore: fix code spelling mistake.
  pkg/merge/aggregator.go
  pkg/merge/aggregator/add_aggregator.go
  pkg/merge/aggregator/add_aggregator_test.go
  pkg/merge/aggregator/avg_aggregator.go
  pkg/merge/aggregator/avg_aggregator_test.go
  pkg/merge/aggregator/max_aggregator.go
  pkg/merge/aggregator/max_aggregator_test.go
  pkg/merge/aggregator/min_aggregator.go
  pkg/merge/aggregator/min_aggregator_test.go
  pkg/merge/impl/group_by/group_by_stream_merge_rows.go
Labels: refactor

#120 [ISSUE #62] Feat configcenter
  .gitignore
  cmd/cmd.go
  docker/conf/bootstrap.yaml
  docker/docker-compose.yaml
  go.mod
  go.sum
  pkg/boot/discovery.go
  pkg/boot/discovery_over_etcd.go
  pkg/boot/discovery_over_file.go
  pkg/boot/discovery_test.go
  pkg/boot/options.go
  pkg/boot/plugin.go
  pkg/config/api.go
  pkg/config/config.go
  pkg/config/etcd.go
  pkg/config/etcd/etcd.go
  pkg/config/etcd/etcd_test.go
  pkg/config/etcd_test.go
  pkg/config/file/file.go
  pkg/config/model.go
  pkg/config/model_test.go
  pkg/util/file/file.go
  testdata/fake_bootstrap.yaml
Labels: enhancement

#124 add license heder & fixes unit test variable name.
  .golangci.yml
  .pre-commit-config.yaml
  docker/Dockerfile
  docker/conf/bootstrap.yaml
  docker/conf/config.yaml
  docker/docker-compose.yaml
  docker/scripts/init.sql
  docker/scripts/sequence.sql
  docker/scripts/sharding.sql
  pkg/boot/options.go
  pkg/boot/plugin.go
  pkg/config/api.go
  pkg/config/config.go
  pkg/config/etcd/etcd.go
  pkg/config/etcd/etcd_test.go
  pkg/config/file/file.go
  pkg/config/model.go
  test/testcontainer_mysql_test.go
  testdata/fake_bootstrap.yaml
Labels: refactor

#133 Support truncate table xxx.
  pkg/executor/redirect.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/proto.go
  pkg/runtime/ast/truncate.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/transparent.go
  pkg/runtime/plan/truncate.go
Labels: enhancement, SQL

#116 schema manager: support table metadata
  pkg/proto/metadata.go
  pkg/proto/runtime.go
  pkg/proto/schema_manager/loader.go
  pkg/proto/schema_manager/loader_test.go
  pkg/runtime/context/context.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/optimize/optimizer_test.go
  pkg/runtime/runtime.go
  testdata/mock_runtime.go
Labels: enhancement

#127 feat:show databases
  pkg/executor/redirect.go
  pkg/mysql/execute_handle.go
  pkg/mysql/fields.go
  pkg/mysql/server.go
  pkg/mysql/utils.go
  pkg/runtime/ast/ast.go
  pkg/runtime/context/context.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/show_databases.go
  pkg/runtime/runtime.go
Labels: enhancement, SQL

#143 add net conn check.
  go.mod
  go.sum
  pkg/mysql/conn.go
Labels: enhancement, Protocol

#141 feat: shard computer implement by javascript
  conf/bootstrap.yaml
  conf/config.yaml
  go.mod
  go.sum
  pkg/boot/discovery.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/rule/shard_script.go
  pkg/runtime/rule/shard_script_test.go
Labels: enhancement, sharding

#147 chore(ci): add auto-build docker image
  .github/workflows/docker-image.yml
Labels: enhancement

#142 Add some metrics
  go.mod
  pkg/executor/redirect.go
  pkg/metrics/metrics.go
  pkg/runtime/runtime.go
Labels: enhancement, observability

#146 feat: add show tables
  pkg/proto/rule/rule.go
  pkg/runtime/optimize/optimizer.go
  pkg/runtime/plan/show_tables.go
Labels: enhancement, sharding

#140 Ftr: add binary & text encode
  pkg/mysql/rows.go
Labels: enhancement, Protocol

#151 add resource pool MySQL conn check
  pkg/mysql/client.go
  pkg/mysql/conn.go
  pkg/runtime/conn_pool.go
  pkg/runtime/runtime.go
Labels: enhancement
