Repository arana-db/arana, pull requests merged in 2023-09, with the labels that each got.

#754 feat(test): add unit test
  pkg/reduce/reduce_test.go
  pkg/util/math/abs_test.go
  pkg/util/math/compare_test.go
  pkg/util/math/decimal_test.go
Labels: test

#763 docs: contributing guide
  README.md
Labels: doc

#761 fix: show tables from database
  pkg/boot/discovery.go
  pkg/runtime/ast/ast_test.go
  pkg/runtime/optimize/dal/show_tables.go
  pkg/runtime/plan/dal/show_tables.go
Labels: bug

#756 add unit test for function (#746)
  pkg/runtime/namespace/namespace.go
  pkg/runtime/namespace/namespace_test.go
Labels: test

#768 fix: send to closed chan in discovery
  go.mod
  pkg/boot/discovery_test.go
  pkg/boot/discovery_watch.go
Labels: bug

#764 test: add unit test for pkg/merge
  pkg/merge/aggregator/loag_agg_test.go
Labels: test

#770 fix(doc): update readme
  README.md
  README_CN.md
  README_ZH.md
Labels: doc

#772 chore(release): prepare for 0.2.0
  CHANGELOG.md
Labels: release
