Repository arana-db/arana, pull requests merged in 2023-01, with the labels that each got.

#574 feat(admin): integrate admin with jwt
  cmd/admin/admin.go
  cmd/start/start.go
  conf/bootstrap.docker.yaml
  conf/bootstrap.local-etcd.yaml
  conf/bootstrap.yaml
  go.mod
  go.sum
  pkg/admin/admin.go
  pkg/admin/jwt.go
  pkg/boot/discovery.go
  pkg/boot/proto.go
  pkg/config/misc.go
  pkg/config/model.go
  pkg/security/tenant.go
Labels: enhancement

#585 feat: implement basic multiple query
  pkg/executor/redirect.go
  pkg/mysql/execute_handle.go
  pkg/mysql/server.go
  pkg/proto/interface.go
  pkg/runtime/function/space_test.go
Labels: enhancement, protocol

#589 Fix: watch event bug in config center
  pkg/boot/watcher.go
  pkg/config/config_watcher.go
Labels: bug

#588 [SQL] Support MySQL IF&IFNULL Function
  pkg/runtime/function/if.go
  pkg/runtime/function/if_null.go
  pkg/runtime/function/if_null_test.go
  pkg/runtime/function/if_test.go
Labels: SQL

#572 feat: Support MySQL CAST_DECIMAL function
  pkg/runtime/function/cast_decimal.go
  pkg/runtime/function/cast_decimal_test.go
Labels: SQL

#599 [Bug] SHOW REPLICA/MASTER STATUS error(#598)
  pkg/runtime/ast/ast.go
Labels: bug

#608 [SQL] Support CHECK TABLE Statement #386
  go.mod
  go.sum
  pkg/executor/redirect.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/check_table.go
  pkg/runtime/ast/proto.go
  pkg/runtime/optimize/ddl/check_table.go
  pkg/runtime/plan/ddl/check_table.go
  test/integration_test.go
Labels: SQL
