Repository arana-db/arana, pull requests merged in 2023-05, with the labels that each got.

#682 Dev hint transform
  go.mod
  go.sum
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/insert.go
  pkg/runtime/ast/model.go
  pkg/runtime/ast/select.go
  pkg/runtime/optimize/dml/insert.go
  test/integration_test.go
Labels: SQL Parser

#679 Support show databases SQL statement with where clause(#672)
  pkg/proto/value.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/create_table.go
  pkg/runtime/ast/expression_atom.go
  pkg/runtime/ast/proto.go
  pkg/runtime/ast/show.go
  pkg/runtime/plan/dal/show_databases.go
  pkg/runtime/plan/dal/show_tables.go
Labels: enhancement

#661 [SQL]:Support show sequence from xxx
  pkg/executor/redirect.go
  pkg/mysql/thead/thead.go
  pkg/proto/sequence.go
  pkg/runtime/ast/ast.go
  pkg/runtime/ast/ast_test.go
  pkg/runtime/ast/proto.go
  pkg/runtime/ast/show.go
  pkg/runtime/optimize/dal/show_create_sequence.go
  pkg/runtime/plan/dal/show_create_sequence.go
  pkg/runtime/plan/dal/show_users.go
  pkg/sequence/group/group.go
  pkg/sequence/snowflake/snowflake.go
Labels: SQL
